

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'

export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'

export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'



export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'

export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'

export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'





export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'

export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'

export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'

export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'






export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'

export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'

export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'

export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'




export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'

export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'

export const MYORDER_CREATE_FAIL = 'MYORDER_CREATE_FAIL'





export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'

export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'

export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'




export const ADMIN_ALL_ORDER_REQUEST = 'ADMIN_ALL_ORDER_REQUEST'

export const ADMIN_ALL_ORDER_SUCCESS = 'ADMIN_ALL_ORDER_SUCCESS'

export const ADMIN_ALL_ORDER_FAIL = 'ADMIN_ALL_ORDER_FAIL'







export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'

export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'

export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'

export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'



export const CUSTOMER_ORDER_IN_PROFILE_REQUEST = 'CUSTOMER_ORDER_IN_PROFILE_REQUEST'

export const CUSTOMER_ORDER_IN_PROFILE_SUCCESS = 'CUSTOMER_ORDER_IN_PROFILE_SUCCESS'

export const CUSTOMER_ORDER_IN_PROFILE_FAIL = 'CUSTOMER_ORDER_IN_PROFILE_FAIL'





export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'

export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'

export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'




export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'

export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'

export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'

export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'